# Generated by Django 5.2 on 2025-04-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='estoque',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='estoque.estoque'),
            preserve_default=False,
        ),
    ]
