# Generated by Django 5.2 on 2025-04-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0002_fornecedor_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='estoque.estoque'),
        ),
    ]
