# Generated by Django 5.2 on 2025-04-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='estoque.estoque')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto')),
            ],
        ),
    ]
