# Generated by Django 5.2 on 2025-04-05 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('movimentacao', '0002_alter_movimentacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
    ]
